### PR TITLE
Makes source no longer required

### PR DESCRIPTION
**Pull request by brandon-groundlight**
This should in theory make v0.18 backwards. compatible

### CODE REVIEW

**Comment by brandon-groundlight** [comment]
I need to check in on the test runner's permissions before I can merge this in, but the branch is here to unblock internal work

**Comment by brandon-groundlight** [comment]
Test runners are updated, should be good to go

**Comment by tyler-romero** [comment]
The fact that source is optional is very unintuitive I think (and hard to determine why by reading the code). Is it possible to add a tag or annotation or something that explians its for compatibility between x version and y version and that in fact it will be returned in y version?

**Review by tyler-romero — APPROVED** [review]
Discussed offline, LGTM after adding some sort of comment about why source is optional and when the version cutoff is

**Pull request merged**
