### PR TITLE
Fix linter issues with __get__

### PR DESCRIPTION
**Pull request by tyler-romero**
Ignore linter issue with __get__

### CODE REVIEW

**Review by robotrapta — APPROVED** [review]

**Review by robotrapta — APPROVED** [review]
I take it back!  This doesn't work!

**Review by robotrapta — CHANGES_REQUESTED** [review]
What I meant was "not approved"!

**Comment by tyler-romero** [comment]
Ok, good that our tests failed here. I instead told the linter to ignore the supposed issue with `__get__`

**Review by robotrapta — APPROVED** [review]
Now that looks good.

**Pull request merged**
